// Common Jira/Slack-style short names. Custom site emoji retain their textual fallback.
const emoji: Readonly<Record<string, string>> = {
  ":smile:": "😄",
  ":smiley:": "😃",
  ":grinning:": "😀",
  ":grin:": "😁",
  ":laughing:": "😆",
  ":satisfied:": "😆",
  ":joy:": "😂",
  ":rofl:": "🤣",
  ":sweat_smile:": "😅",
  ":slightly_smiling_face:": "🙂",
  ":upside_down_face:": "🙃",
  ":wink:": "😉",
  ":blush:": "😊",
  ":innocent:": "😇",
  ":heart_eyes:": "😍",
  ":kissing_heart:": "😘",
  ":sunglasses:": "😎",
  ":nerd_face:": "🤓",
  ":thinking:": "🤔",
  ":thinking_face:": "🤔",
  ":face_with_raised_eyebrow:": "🤨",
  ":neutral_face:": "😐",
  ":expressionless:": "😑",
  ":no_mouth:": "😶",
  ":rolling_eyes:": "🙄",
  ":smirk:": "😏",
  ":unamused:": "😒",
  ":confused:": "😕",
  ":worried:": "😟",
  ":disappointed:": "😞",
  ":cry:": "😢",
  ":sob:": "😭",
  ":angry:": "😠",
  ":rage:": "😡",
  ":scream:": "😱",
  ":flushed:": "😳",
  ":sweat:": "😓",
  ":relieved:": "😌",
  ":sleeping:": "😴",
  ":zipper_mouth_face:": "🤐",
  ":facepalm:": "🤦",
  ":shrug:": "🤷",
  ":thumbsup:": "👍",
  ":+1:": "👍",
  ":thumbsdown:": "👎",
  ":-1:": "👎",
  ":ok_hand:": "👌",
  ":clap:": "👏",
  ":raised_hands:": "🙌",
  ":pray:": "🙏",
  ":wave:": "👋",
  ":handshake:": "🤝",
  ":muscle:": "💪",
  ":v:": "✌️",
  ":point_up:": "☝️",
  ":point_down:": "👇",
  ":point_left:": "👈",
  ":point_right:": "👉",
  ":eyes:": "👀",
  ":heart:": "❤️",
  ":blue_heart:": "💙",
  ":green_heart:": "💚",
  ":broken_heart:": "💔",
  ":tada:": "🎉",
  ":confetti_ball:": "🎊",
  ":rocket:": "🚀",
  ":fire:": "🔥",
  ":sparkles:": "✨",
  ":star:": "⭐",
  ":star2:": "🌟",
  ":100:": "💯",
  ":white_check_mark:": "✅",
  ":check_mark:": "✔️",
  ":heavy_check_mark:": "✔️",
  ":ballot_box_with_check:": "☑️",
  ":x:": "❌",
  ":negative_squared_cross_mark:": "❎",
  ":warning:": "⚠️",
  ":no_entry:": "⛔",
  ":no_entry_sign:": "🚫",
  ":exclamation:": "❗",
  ":question:": "❓",
  ":information_source:": "ℹ️",
  ":bulb:": "💡",
  ":bug:": "🐛",
  ":wrench:": "🔧",
  ":hammer:": "🔨",
  ":gear:": "⚙️",
  ":construction:": "🚧",
  ":mag:": "🔍",
  ":lock:": "🔒",
  ":key:": "🔑",
  ":link:": "🔗",
  ":memo:": "📝",
  ":hourglass_flowing_sand:": "⏳",
  ":coffee:": "☕",
  ":skin-tone-2:": "🏻",
  ":skin-tone-3:": "🏼",
  ":skin-tone-4:": "🏽",
  ":skin-tone-5:": "🏾",
  ":skin-tone-6:": "🏿",
}

export function adfEmoji(attrs: Record<string, unknown> | undefined) {
  const label = typeof attrs?.text === "string" ? attrs.text.trim() : ""
  const shortName = typeof attrs?.shortName === "string" ? attrs.shortName.trim() : ""
  return replaceEmojiShortcodes(label || shortName)
}

export function replaceEmojiShortcodes(value: string) {
  return value.replace(/:[a-z0-9_+-]+:/gi, (name) => emoji[name.toLowerCase()] ?? name)
}
