import { expect, story } from "../../storybook/playwright/story"

story("selects a branch with the keyboard and closes its popup", async ({ mount, page }) => {
  await mount("boc-deployments--default")
  const dialog = page.getByRole("dialog")
  const branch = dialog.getByRole("combobox", { name: "Branch" })

  await expect(branch).toHaveValue("SHOP-617")
  await branch.fill("SHOP-617")
  const popup = page.locator(".deployment-branch-menu")
  await expect(popup).toBeVisible()
  await expect(popup.getByText("SHOP-617-product-gallery", { exact: true })).toBeVisible()
  await page.keyboard.press("ArrowDown")
  await page.keyboard.press("Enter")
  await expect(popup).not.toBeVisible()
  await expect(branch).toHaveValue("SHOP-617-product-gallery")
  await expect(dialog.getByRole("button", { name: "Deploy to dev-01" })).toBeEnabled()
  await dialog.locator(".deployment-branch-trigger").click()
  await expect(popup).toBeVisible()
  await popup.getByRole("option", { name: "SHOP-617-product-gallery" }).click()
  await expect(popup).not.toBeVisible()
  await dialog.locator(".deployment-branch-trigger").click()
  await expect(popup).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(popup).not.toBeVisible()
  await expect(dialog).toBeVisible()
})

story("keeps workflow search and inline options stable", async ({ mount, page }) => {
  await mount("boc-deployments--default")
  const dialog = page.getByRole("dialog")
  const branch = dialog.getByRole("combobox", { name: "Branch" })
  await branch.fill("SHOP-617")
  await expect(
    page.locator(".deployment-branch-menu").getByText("SHOP-617-product-gallery", { exact: true }),
  ).toBeVisible()
  await page.keyboard.press("ArrowDown")
  await page.keyboard.press("Enter")

  const workflows = dialog.getByRole("group", { name: "Workflows" })
  const workflowList = workflows.locator(".deployment-workflow-list")
  const choices = workflowList.getByRole("checkbox")
  await expect(choices.first()).toBeChecked()
  await expect(choices).toHaveCount(2)
  const bounds = await dialog.boundingBox()
  await workflows.getByRole("textbox", { name: "Search workflows" }).fill("Admin")
  await expect(choices).toHaveCount(2)
  await expect(workflowList.locator("mark").first()).toHaveText("Admin")
  expect(await dialog.boundingBox()).toEqual(bounds)
  const admin = workflowList
    .getByRole("row")
    .filter({ has: page.getByRole("checkbox", { name: "Admin app-admin.yml" }) })
  const selectedWorkflowOption = admin.getByRole("switch")
  await expect(selectedWorkflowOption).toBeDisabled()
  await workflowList.getByText("Admin", { exact: true }).click()
  await workflows.getByRole("textbox", { name: "Search workflows" }).fill("")
  await expect(choices.nth(1)).toBeChecked()
  await expect(selectedWorkflowOption).toBeEnabled()
  await selectedWorkflowOption.focus()
  await page.keyboard.press("Space")
  const changed = await selectedWorkflowOption.isChecked()
  expect(changed).toBe(false)
  await workflowList.getByText("Admin", { exact: true }).click()
  await expect(choices.nth(1)).not.toBeChecked()
  await expect(selectedWorkflowOption).toBeDisabled()
  await workflowList.getByText("Admin", { exact: true }).click()
  await expect(selectedWorkflowOption).toBeChecked({ checked: changed })
  await expect(workflowList.getByRole("row").filter({ hasText: "Shop" }).getByRole("switch").first()).toBeChecked()
  await expect(dialog.getByRole("button", { name: "Deploy to dev-01" })).toBeEnabled()
  expect(await dialog.boundingBox()).toEqual(bounds)
  await workflows.getByRole("textbox", { name: "Search workflows" }).fill("missing[")
  await expect(workflows.getByText("No matching workflows.")).toBeVisible()
  await expect(choices).toHaveCount(2)
  expect(await dialog.boundingBox()).toEqual(bounds)
})

story("finds workflows below the fold and edits inline choices", async ({ mount, page }) => {
  await mount("boc-deployments--workflow-table", { globals: { theme: "dark" } })
  const dialog = page.getByRole("dialog")
  const list = dialog.locator(".deployment-workflow-list")
  await expect(list.getByRole("checkbox")).toHaveCount(16)
  const bounds = await dialog.boundingBox()
  const search = dialog.getByRole("textbox", { name: "Search workflows" })
  await search.fill("api")
  await expect(list.locator("[data-match]")).toContainText("app-api-ap")
  await search.press("Shift+Enter")
  await expect(list.locator("[data-match]")).toContainText("app-api-users")
  expect(await list.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  await dialog.getByRole("button", { name: "Next matching workflow" }).click()
  await expect(list.locator("[data-match]")).toContainText("app-api-ap")
  await search.fill("worker")
  const worker = list.getByRole("row").filter({ hasText: "app-worker" })
  await worker.getByText("app-worker", { exact: true }).click()
  const mode = worker.getByRole("button", { name: /Mode/ })
  await expect(mode).toBeEnabled()
  await mode.click()
  await page.getByRole("option", { name: "fast", exact: true }).click()
  await expect(mode).toContainText("fast")
  await expect(dialog.getByRole("button", { name: "Deploy to dev-01" })).toBeEnabled()
  expect(await dialog.boundingBox()).toEqual(bounds)
})

story("keeps only the workflow table scrollable in a short dialog", async ({ mount, page }) => {
  await page.setViewportSize({ width: 900, height: 620 })
  await mount("boc-deployments--workflow-table", { globals: { theme: "dark" } })
  const dialog = page.getByRole("dialog")
  const list = dialog.locator(".deployment-workflow-list")
  await expect(list.getByRole("checkbox")).toHaveCount(16)
  const body = dialog.locator(".deployment-preflight-body")
  expect(await body.evaluate((element) => element.scrollHeight <= element.clientHeight)).toBe(true)
  const header = await dialog.locator(".deployment-branch").boundingBox()
  const footer = await dialog.locator('[data-slot="dialog-footer"]').boundingBox()
  await dialog.getByRole("textbox", { name: "Search workflows" }).fill("worker")
  await expect(list.locator("[data-match] mark")).toHaveText("worker")
  expect(await list.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  expect(await body.evaluate((element) => element.scrollTop)).toBe(0)
  expect(await dialog.locator(".deployment-branch").boundingBox()).toEqual(header)
  expect(await dialog.locator('[data-slot="dialog-footer"]').boundingBox()).toEqual(footer)
  await expect(dialog.getByRole("button", { name: "Deploy to dev-01" })).toBeInViewport()
})

story("retries a failed preparation without dispatching", async ({ mount, page }) => {
  await mount("boc-deployments--retry")
  const dialog = page.getByRole("dialog")
  await expect(dialog.getByRole("alert")).toBeVisible()
  const deploy = dialog.getByRole("button", { name: "Deploy to dev-01" })
  await expect(deploy).toBeDisabled()
  await dialog.getByRole("button", { name: "Check again" }).click()
  await expect(deploy).toBeEnabled()
})

story("shows slow preparation and an expired prepared plan", async ({ mount, page }) => {
  await mount("boc-deployments--slow-preparation")
  const slow = page.getByRole("dialog")
  await expect(slow.getByRole("button", { name: "Checking…" })).toBeDisabled()
  await expect(slow.getByRole("button", { name: "Deploy to dev-01" })).toBeEnabled()

  await mount("boc-deployments--expired")
  const expired = page.getByRole("dialog")
  await expect(expired.getByText("Check this deployment again to continue.", { exact: true })).toBeVisible()
  await expect(expired.getByRole("button", { name: "Check again" })).toBeVisible()
  await expect(expired.getByRole("button", { name: "Deploy to dev-01" })).toBeDisabled()
})

story("renders reset as a readonly summary", async ({ mount, page }) => {
  await mount("boc-deployments--reset")
  const dialog = page.getByRole("dialog")
  await expect(dialog.getByRole("heading", { name: "Reset dev-01" })).toBeVisible()
  await expect(dialog.getByText("master", { exact: true })).toBeVisible()
  await expect(
    dialog.getByText("Deploy master with tests enabled, without a forced rebuild or regression tests."),
  ).toBeVisible()
  await expect(dialog.getByRole("combobox", { name: "Branch" })).toHaveCount(0)
  await expect(dialog.getByRole("checkbox")).toHaveCount(0)
  await expect(dialog.getByRole("button", { name: "Reset dev-01" })).toBeEnabled()
})

story("fits the deployment preflight in narrow forced RTL", async ({ mount, page }) => {
  await page.setViewportSize({ width: 375, height: 700 })
  await mount("boc-deployments--narrow-rtl", {
    globals: { direction: "rtl", locale: "en", theme: "dark" },
  })
  const dialog = page.getByRole("dialog")
  await expect(dialog).toHaveCSS("direction", "rtl")
  await expect(dialog.getByRole("button", { name: "Close deployment dialog" })).toBeInViewport()
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  const control = await dialog.locator(".deployment-branch-control").boundingBox()
  const trigger = await dialog.locator(".deployment-branch-trigger").boundingBox()
  if (!control || !trigger) throw new Error("Expected branch picker controls")
  expect(trigger.x).toBeGreaterThanOrEqual(control.x)
  expect(trigger.x + trigger.width).toBeLessThanOrEqual(control.x + control.width)
  const branch = dialog.getByRole("combobox", { name: "Branch" })
  await expect(branch).toHaveCSS("direction", "ltr")
  await branch.fill("SHOP-61")
  await expect(page.locator(".deployment-branch-menu")).toBeInViewport()
})

story("saves and clears optional development site credentials", async ({ mount, page }) => {
  await mount("boc-deployments--settings")
  const dialog = page.getByRole("dialog")
  const username = dialog.locator('input[name="deployment-site-username"]')
  const password = dialog.locator('input[name="deployment-site-password"]')
  await expect(password).toHaveAttribute("type", "password")
  await username.fill("demo")
  await password.fill("p@ss:/?#")
  await dialog.getByRole("button", { name: "Save and check" }).click()
  await expect(dialog.getByText("Settings saved. Fleet readiness was checked again.")).toBeVisible()
  await dialog.getByRole("button", { name: "Close deployment settings" }).click()
  await page.getByRole("button", { name: "Open deployment settings" }).click()
  await expect(username).toHaveValue("demo")
  await expect(password).toHaveValue("p@ss:/?#")
  await username.fill("")
  await password.fill("")
  await dialog.getByRole("button", { name: "Save and check" }).click()
  await expect(dialog.getByText("Settings saved. Fleet readiness was checked again.")).toBeVisible()
  await dialog.getByRole("button", { name: "Close deployment settings" }).click()
  await page.getByRole("button", { name: "Open deployment settings" }).click()
  await expect(username).toHaveValue("")
  await expect(password).toHaveValue("")
})
