export { bocExtensions, byId, type BocCommand, type BocExtension, type BocScreenProps } from "../registry"
export { BocDesktopProvider, useBocDesktop } from "./desktop"
export { BocHostProvider, useBocHost, type BocHost, type BocTerminalInput } from "./host"
export { bocEnglish, createBocTranslator, type BocI18nKey, type BocTranslator } from "./i18n"
export { BocScreen, bocScreenState } from "./screen"
